title: Carlos A. Sanchez
description: Technical operations leader, IT professor, and builder of practical technology solutions.
theme: jekyll-theme-minimal

url: "https://iscenigmax.github.io"
baseurl: ""

author:
  name: Carlos A. Sanchez

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
lang: es

github_username: iscenigmax
twitter_username: iscenigmax

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - node_modules
